// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: v1/manager/leaderboard/leaderboard.proto

package leaderboard

import (
	manager "github.com/megakuul/zen/pkg/api/v1/manager"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Score         *float64               `protobuf:"fixed64,1,opt,name=score,proto3,oneof" json:"score,omitempty"`
	Streak        *int64                 `protobuf:"varint,2,opt,name=streak,proto3,oneof" json:"streak,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_v1_manager_leaderboard_leaderboard_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_manager_leaderboard_leaderboard_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_v1_manager_leaderboard_leaderboard_proto_rawDescGZIP(), []int{0}
}

func (x *GetRequest) GetScore() float64 {
	if x != nil && x.Score != nil {
		return *x.Score
	}
	return 0
}

func (x *GetRequest) GetStreak() int64 {
	if x != nil && x.Streak != nil {
		return *x.Streak
	}
	return 0
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*manager.User        `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_v1_manager_leaderboard_leaderboard_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_manager_leaderboard_leaderboard_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_v1_manager_leaderboard_leaderboard_proto_rawDescGZIP(), []int{1}
}

func (x *GetResponse) GetUsers() []*manager.User {
	if x != nil {
		return x.Users
	}
	return nil
}

var File_v1_manager_leaderboard_leaderboard_proto protoreflect.FileDescriptor

const file_v1_manager_leaderboard_leaderboard_proto_rawDesc = "" +
	"\n" +
	"(v1/manager/leaderboard/leaderboard.proto\x12\x16v1.manager.leaderboard\x1a\x15v1/manager/user.proto\"Y\n" +
	"\n" +
	"GetRequest\x12\x19\n" +
	"\x05score\x18\x01 \x01(\x01H\x00R\x05score\x88\x01\x01\x12\x1b\n" +
	"\x06streak\x18\x02 \x01(\x03H\x01R\x06streak\x88\x01\x01B\b\n" +
	"\x06_scoreB\t\n" +
	"\a_streak\"5\n" +
	"\vGetResponse\x12&\n" +
	"\x05users\x18\x01 \x03(\v2\x10.v1.manager.UserR\x05users2f\n" +
	"\x12LeaderboardService\x12P\n" +
	"\x03Get\x12\".v1.manager.leaderboard.GetRequest\x1a#.v1.manager.leaderboard.GetResponse\"\x00B8Z6github.com/megakuul/zen/pkg/api/v1/manager/leaderboardb\x06proto3"

var (
	file_v1_manager_leaderboard_leaderboard_proto_rawDescOnce sync.Once
	file_v1_manager_leaderboard_leaderboard_proto_rawDescData []byte
)

func file_v1_manager_leaderboard_leaderboard_proto_rawDescGZIP() []byte {
	file_v1_manager_leaderboard_leaderboard_proto_rawDescOnce.Do(func() {
		file_v1_manager_leaderboard_leaderboard_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_manager_leaderboard_leaderboard_proto_rawDesc), len(file_v1_manager_leaderboard_leaderboard_proto_rawDesc)))
	})
	return file_v1_manager_leaderboard_leaderboard_proto_rawDescData
}

var file_v1_manager_leaderboard_leaderboard_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1_manager_leaderboard_leaderboard_proto_goTypes = []any{
	(*GetRequest)(nil),   // 0: v1.manager.leaderboard.GetRequest
	(*GetResponse)(nil),  // 1: v1.manager.leaderboard.GetResponse
	(*manager.User)(nil), // 2: v1.manager.User
}
var file_v1_manager_leaderboard_leaderboard_proto_depIdxs = []int32{
	2, // 0: v1.manager.leaderboard.GetResponse.users:type_name -> v1.manager.User
	0, // 1: v1.manager.leaderboard.LeaderboardService.Get:input_type -> v1.manager.leaderboard.GetRequest
	1, // 2: v1.manager.leaderboard.LeaderboardService.Get:output_type -> v1.manager.leaderboard.GetResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_v1_manager_leaderboard_leaderboard_proto_init() }
func file_v1_manager_leaderboard_leaderboard_proto_init() {
	if File_v1_manager_leaderboard_leaderboard_proto != nil {
		return
	}
	file_v1_manager_leaderboard_leaderboard_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_manager_leaderboard_leaderboard_proto_rawDesc), len(file_v1_manager_leaderboard_leaderboard_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_manager_leaderboard_leaderboard_proto_goTypes,
		DependencyIndexes: file_v1_manager_leaderboard_leaderboard_proto_depIdxs,
		MessageInfos:      file_v1_manager_leaderboard_leaderboard_proto_msgTypes,
	}.Build()
	File_v1_manager_leaderboard_leaderboard_proto = out.File
	file_v1_manager_leaderboard_leaderboard_proto_goTypes = nil
	file_v1_manager_leaderboard_leaderboard_proto_depIdxs = nil
}
