// @generated by protoc-gen-es v2.7.0 with parameter "target=ts"
// @generated from file v1/scheduler/planning/planning.proto (package v1.scheduler.planning, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Event } from "../event_pb";
import { file_v1_scheduler_event } from "../event_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file v1/scheduler/planning/planning.proto.
 */
export const file_v1_scheduler_planning_planning: GenFile = /*@__PURE__*/
  fileDesc("CiR2MS9zY2hlZHVsZXIvcGxhbm5pbmcvcGxhbm5pbmcucHJvdG8SFXYxLnNjaGVkdWxlci5wbGFubmluZyIqCgpHZXRSZXF1ZXN0Eg0KBXNpbmNlGAEgASgDEg0KBXVudGlsGAIgASgDIjIKC0dldFJlc3BvbnNlEiMKBmV2ZW50cxgBIAMoCzITLnYxLnNjaGVkdWxlci5FdmVudCIzCg1VcHNlcnRSZXF1ZXN0EiIKBWV2ZW50GAEgASgLMhMudjEuc2NoZWR1bGVyLkV2ZW50IhAKDlVwc2VydFJlc3BvbnNlIhsKDURlbGV0ZVJlcXVlc3QSCgoCaWQYASABKAkiEAoORGVsZXRlUmVzcG9uc2UykwIKD1BsYW5uaW5nU2VydmljZRJOCgNHZXQSIS52MS5zY2hlZHVsZXIucGxhbm5pbmcuR2V0UmVxdWVzdBoiLnYxLnNjaGVkdWxlci5wbGFubmluZy5HZXRSZXNwb25zZSIAElcKBlVwc2VydBIkLnYxLnNjaGVkdWxlci5wbGFubmluZy5VcHNlcnRSZXF1ZXN0GiUudjEuc2NoZWR1bGVyLnBsYW5uaW5nLlVwc2VydFJlc3BvbnNlIgASVwoGRGVsZXRlEiQudjEuc2NoZWR1bGVyLnBsYW5uaW5nLkRlbGV0ZVJlcXVlc3QaJS52MS5zY2hlZHVsZXIucGxhbm5pbmcuRGVsZXRlUmVzcG9uc2UiAEI3WjVnaXRodWIuY29tL21lZ2FrdXVsL3plbi9wa2cvYXBpL3YxL3NjaGVkdWxlci9wbGFubmluZ2IGcHJvdG8z", [file_v1_scheduler_event]);

/**
 * @generated from message v1.scheduler.planning.GetRequest
 */
export type GetRequest = Message<"v1.scheduler.planning.GetRequest"> & {
  /**
   * @generated from field: int64 since = 1;
   */
  since: bigint;

  /**
   * @generated from field: int64 until = 2;
   */
  until: bigint;
};

/**
 * Describes the message v1.scheduler.planning.GetRequest.
 * Use `create(GetRequestSchema)` to create a new message.
 */
export const GetRequestSchema: GenMessage<GetRequest> = /*@__PURE__*/
  messageDesc(file_v1_scheduler_planning_planning, 0);

/**
 * @generated from message v1.scheduler.planning.GetResponse
 */
export type GetResponse = Message<"v1.scheduler.planning.GetResponse"> & {
  /**
   * @generated from field: repeated v1.scheduler.Event events = 1;
   */
  events: Event[];
};

/**
 * Describes the message v1.scheduler.planning.GetResponse.
 * Use `create(GetResponseSchema)` to create a new message.
 */
export const GetResponseSchema: GenMessage<GetResponse> = /*@__PURE__*/
  messageDesc(file_v1_scheduler_planning_planning, 1);

/**
 * @generated from message v1.scheduler.planning.UpsertRequest
 */
export type UpsertRequest = Message<"v1.scheduler.planning.UpsertRequest"> & {
  /**
   * @generated from field: v1.scheduler.Event event = 1;
   */
  event?: Event;
};

/**
 * Describes the message v1.scheduler.planning.UpsertRequest.
 * Use `create(UpsertRequestSchema)` to create a new message.
 */
export const UpsertRequestSchema: GenMessage<UpsertRequest> = /*@__PURE__*/
  messageDesc(file_v1_scheduler_planning_planning, 2);

/**
 * @generated from message v1.scheduler.planning.UpsertResponse
 */
export type UpsertResponse = Message<"v1.scheduler.planning.UpsertResponse"> & {
};

/**
 * Describes the message v1.scheduler.planning.UpsertResponse.
 * Use `create(UpsertResponseSchema)` to create a new message.
 */
export const UpsertResponseSchema: GenMessage<UpsertResponse> = /*@__PURE__*/
  messageDesc(file_v1_scheduler_planning_planning, 3);

/**
 * @generated from message v1.scheduler.planning.DeleteRequest
 */
export type DeleteRequest = Message<"v1.scheduler.planning.DeleteRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message v1.scheduler.planning.DeleteRequest.
 * Use `create(DeleteRequestSchema)` to create a new message.
 */
export const DeleteRequestSchema: GenMessage<DeleteRequest> = /*@__PURE__*/
  messageDesc(file_v1_scheduler_planning_planning, 4);

/**
 * @generated from message v1.scheduler.planning.DeleteResponse
 */
export type DeleteResponse = Message<"v1.scheduler.planning.DeleteResponse"> & {
};

/**
 * Describes the message v1.scheduler.planning.DeleteResponse.
 * Use `create(DeleteResponseSchema)` to create a new message.
 */
export const DeleteResponseSchema: GenMessage<DeleteResponse> = /*@__PURE__*/
  messageDesc(file_v1_scheduler_planning_planning, 5);

/**
 * @generated from service v1.scheduler.planning.PlanningService
 */
export const PlanningService: GenService<{
  /**
   * @generated from rpc v1.scheduler.planning.PlanningService.Get
   */
  get: {
    methodKind: "unary";
    input: typeof GetRequestSchema;
    output: typeof GetResponseSchema;
  },
  /**
   * @generated from rpc v1.scheduler.planning.PlanningService.Upsert
   */
  upsert: {
    methodKind: "unary";
    input: typeof UpsertRequestSchema;
    output: typeof UpsertResponseSchema;
  },
  /**
   * @generated from rpc v1.scheduler.planning.PlanningService.Delete
   */
  delete: {
    methodKind: "unary";
    input: typeof DeleteRequestSchema;
    output: typeof DeleteResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_v1_scheduler_planning_planning, 0);

