// @generated by protoc-gen-es v2.7.0 with parameter "target=ts"
// @generated from file v1/manager/leaderboard/leaderboard.proto (package v1.manager.leaderboard, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { User } from "../user_pb";
import { file_v1_manager_user } from "../user_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file v1/manager/leaderboard/leaderboard.proto.
 */
export const file_v1_manager_leaderboard_leaderboard: GenFile = /*@__PURE__*/
  fileDesc("Cih2MS9tYW5hZ2VyL2xlYWRlcmJvYXJkL2xlYWRlcmJvYXJkLnByb3RvEhZ2MS5tYW5hZ2VyLmxlYWRlcmJvYXJkIkoKCkdldFJlcXVlc3QSEgoFc2NvcmUYASABKAFIAIgBARITCgZzdHJlYWsYAiABKANIAYgBAUIICgZfc2NvcmVCCQoHX3N0cmVhayIuCgtHZXRSZXNwb25zZRIfCgV1c2VycxgBIAMoCzIQLnYxLm1hbmFnZXIuVXNlcjJmChJMZWFkZXJib2FyZFNlcnZpY2USUAoDR2V0EiIudjEubWFuYWdlci5sZWFkZXJib2FyZC5HZXRSZXF1ZXN0GiMudjEubWFuYWdlci5sZWFkZXJib2FyZC5HZXRSZXNwb25zZSIAQjhaNmdpdGh1Yi5jb20vbWVnYWt1dWwvemVuL3BrZy9hcGkvdjEvbWFuYWdlci9sZWFkZXJib2FyZGIGcHJvdG8z", [file_v1_manager_user]);

/**
 * @generated from message v1.manager.leaderboard.GetRequest
 */
export type GetRequest = Message<"v1.manager.leaderboard.GetRequest"> & {
  /**
   * @generated from field: optional double score = 1;
   */
  score?: number;

  /**
   * @generated from field: optional int64 streak = 2;
   */
  streak?: bigint;
};

/**
 * Describes the message v1.manager.leaderboard.GetRequest.
 * Use `create(GetRequestSchema)` to create a new message.
 */
export const GetRequestSchema: GenMessage<GetRequest> = /*@__PURE__*/
  messageDesc(file_v1_manager_leaderboard_leaderboard, 0);

/**
 * @generated from message v1.manager.leaderboard.GetResponse
 */
export type GetResponse = Message<"v1.manager.leaderboard.GetResponse"> & {
  /**
   * @generated from field: repeated v1.manager.User users = 1;
   */
  users: User[];
};

/**
 * Describes the message v1.manager.leaderboard.GetResponse.
 * Use `create(GetResponseSchema)` to create a new message.
 */
export const GetResponseSchema: GenMessage<GetResponse> = /*@__PURE__*/
  messageDesc(file_v1_manager_leaderboard_leaderboard, 1);

/**
 * @generated from service v1.manager.leaderboard.LeaderboardService
 */
export const LeaderboardService: GenService<{
  /**
   * @generated from rpc v1.manager.leaderboard.LeaderboardService.Get
   */
  get: {
    methodKind: "unary";
    input: typeof GetRequestSchema;
    output: typeof GetResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_v1_manager_leaderboard_leaderboard, 0);

