// @generated by protoc-gen-es v2.7.0 with parameter "target=ts"
// @generated from file v1/manager/authentication/authentication.proto (package v1.manager.authentication, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file v1/manager/authentication/authentication.proto.
 */
export const file_v1_manager_authentication_authentication: GenFile = /*@__PURE__*/
  fileDesc("Ci52MS9tYW5hZ2VyL2F1dGhlbnRpY2F0aW9uL2F1dGhlbnRpY2F0aW9uLnByb3RvEhl2MS5tYW5hZ2VyLmF1dGhlbnRpY2F0aW9uIjQKCkdldFJlcXVlc3QSEAoIdmVyaWZpZXIYASABKAkSFAoMYXV0b19yZWZyZXNoGAIgASgIIhwKC0dldFJlc3BvbnNlEg0KBXRva2VuGAEgASgJIg8KDVJldm9rZVJlcXVlc3QiEAoOUmV2b2tlUmVzcG9uc2Uy0AEKFUF1dGhlbnRpY2F0aW9uU2VydmljZRJWCgNHZXQSJS52MS5tYW5hZ2VyLmF1dGhlbnRpY2F0aW9uLkdldFJlcXVlc3QaJi52MS5tYW5hZ2VyLmF1dGhlbnRpY2F0aW9uLkdldFJlc3BvbnNlIgASXwoGUmV2b2tlEigudjEubWFuYWdlci5hdXRoZW50aWNhdGlvbi5SZXZva2VSZXF1ZXN0GikudjEubWFuYWdlci5hdXRoZW50aWNhdGlvbi5SZXZva2VSZXNwb25zZSIAQjtaOWdpdGh1Yi5jb20vbWVnYWt1dWwvemVuL3BrZy9hcGkvdjEvbWFuYWdlci9hdXRoZW50aWNhdGlvbmIGcHJvdG8z");

/**
 * @generated from message v1.manager.authentication.GetRequest
 */
export type GetRequest = Message<"v1.manager.authentication.GetRequest"> & {
  /**
   * @generated from field: string verifier = 1;
   */
  verifier: string;

  /**
   * @generated from field: bool auto_refresh = 2;
   */
  autoRefresh: boolean;
};

/**
 * Describes the message v1.manager.authentication.GetRequest.
 * Use `create(GetRequestSchema)` to create a new message.
 */
export const GetRequestSchema: GenMessage<GetRequest> = /*@__PURE__*/
  messageDesc(file_v1_manager_authentication_authentication, 0);

/**
 * @generated from message v1.manager.authentication.GetResponse
 */
export type GetResponse = Message<"v1.manager.authentication.GetResponse"> & {
  /**
   * @generated from field: string token = 1;
   */
  token: string;
};

/**
 * Describes the message v1.manager.authentication.GetResponse.
 * Use `create(GetResponseSchema)` to create a new message.
 */
export const GetResponseSchema: GenMessage<GetResponse> = /*@__PURE__*/
  messageDesc(file_v1_manager_authentication_authentication, 1);

/**
 * @generated from message v1.manager.authentication.RevokeRequest
 */
export type RevokeRequest = Message<"v1.manager.authentication.RevokeRequest"> & {
};

/**
 * Describes the message v1.manager.authentication.RevokeRequest.
 * Use `create(RevokeRequestSchema)` to create a new message.
 */
export const RevokeRequestSchema: GenMessage<RevokeRequest> = /*@__PURE__*/
  messageDesc(file_v1_manager_authentication_authentication, 2);

/**
 * @generated from message v1.manager.authentication.RevokeResponse
 */
export type RevokeResponse = Message<"v1.manager.authentication.RevokeResponse"> & {
};

/**
 * Describes the message v1.manager.authentication.RevokeResponse.
 * Use `create(RevokeResponseSchema)` to create a new message.
 */
export const RevokeResponseSchema: GenMessage<RevokeResponse> = /*@__PURE__*/
  messageDesc(file_v1_manager_authentication_authentication, 3);

/**
 * @generated from service v1.manager.authentication.AuthenticationService
 */
export const AuthenticationService: GenService<{
  /**
   * @generated from rpc v1.manager.authentication.AuthenticationService.Get
   */
  get: {
    methodKind: "unary";
    input: typeof GetRequestSchema;
    output: typeof GetResponseSchema;
  },
  /**
   * @generated from rpc v1.manager.authentication.AuthenticationService.Revoke
   */
  revoke: {
    methodKind: "unary";
    input: typeof RevokeRequestSchema;
    output: typeof RevokeResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_v1_manager_authentication_authentication, 0);

