// @generated by protoc-gen-es v2.7.0 with parameter "target=ts"
// @generated from file v1/manager/authentication/authentication.proto (package v1.manager.authentication, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Verifier } from "../verifier_pb";
import { file_v1_manager_verifier } from "../verifier_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file v1/manager/authentication/authentication.proto.
 */
export const file_v1_manager_authentication_authentication: GenFile = /*@__PURE__*/
  fileDesc("Ci52MS9tYW5hZ2VyL2F1dGhlbnRpY2F0aW9uL2F1dGhlbnRpY2F0aW9uLnByb3RvEhl2MS5tYW5hZ2VyLmF1dGhlbnRpY2F0aW9uIkwKDExvZ2luUmVxdWVzdBImCgh2ZXJpZmllchgBIAEoCzIULnYxLm1hbmFnZXIuVmVyaWZpZXISFAoMYXV0b19yZWZyZXNoGAIgASgIIh4KDUxvZ2luUmVzcG9uc2USDQoFdG9rZW4YASABKAkiDwoNTG9nb3V0UmVxdWVzdCIQCg5Mb2dvdXRSZXNwb25zZTLWAQoVQXV0aGVudGljYXRpb25TZXJ2aWNlElwKBUxvZ2luEicudjEubWFuYWdlci5hdXRoZW50aWNhdGlvbi5Mb2dpblJlcXVlc3QaKC52MS5tYW5hZ2VyLmF1dGhlbnRpY2F0aW9uLkxvZ2luUmVzcG9uc2UiABJfCgZMb2dvdXQSKC52MS5tYW5hZ2VyLmF1dGhlbnRpY2F0aW9uLkxvZ291dFJlcXVlc3QaKS52MS5tYW5hZ2VyLmF1dGhlbnRpY2F0aW9uLkxvZ291dFJlc3BvbnNlIgBCO1o5Z2l0aHViLmNvbS9tZWdha3V1bC96ZW4vcGtnL2FwaS92MS9tYW5hZ2VyL2F1dGhlbnRpY2F0aW9uYgZwcm90bzM", [file_v1_manager_verifier]);

/**
 * @generated from message v1.manager.authentication.LoginRequest
 */
export type LoginRequest = Message<"v1.manager.authentication.LoginRequest"> & {
  /**
   * @generated from field: v1.manager.Verifier verifier = 1;
   */
  verifier?: Verifier;

  /**
   * @generated from field: bool auto_refresh = 2;
   */
  autoRefresh: boolean;
};

/**
 * Describes the message v1.manager.authentication.LoginRequest.
 * Use `create(LoginRequestSchema)` to create a new message.
 */
export const LoginRequestSchema: GenMessage<LoginRequest> = /*@__PURE__*/
  messageDesc(file_v1_manager_authentication_authentication, 0);

/**
 * @generated from message v1.manager.authentication.LoginResponse
 */
export type LoginResponse = Message<"v1.manager.authentication.LoginResponse"> & {
  /**
   * @generated from field: string token = 1;
   */
  token: string;
};

/**
 * Describes the message v1.manager.authentication.LoginResponse.
 * Use `create(LoginResponseSchema)` to create a new message.
 */
export const LoginResponseSchema: GenMessage<LoginResponse> = /*@__PURE__*/
  messageDesc(file_v1_manager_authentication_authentication, 1);

/**
 * @generated from message v1.manager.authentication.LogoutRequest
 */
export type LogoutRequest = Message<"v1.manager.authentication.LogoutRequest"> & {
};

/**
 * Describes the message v1.manager.authentication.LogoutRequest.
 * Use `create(LogoutRequestSchema)` to create a new message.
 */
export const LogoutRequestSchema: GenMessage<LogoutRequest> = /*@__PURE__*/
  messageDesc(file_v1_manager_authentication_authentication, 2);

/**
 * @generated from message v1.manager.authentication.LogoutResponse
 */
export type LogoutResponse = Message<"v1.manager.authentication.LogoutResponse"> & {
};

/**
 * Describes the message v1.manager.authentication.LogoutResponse.
 * Use `create(LogoutResponseSchema)` to create a new message.
 */
export const LogoutResponseSchema: GenMessage<LogoutResponse> = /*@__PURE__*/
  messageDesc(file_v1_manager_authentication_authentication, 3);

/**
 * @generated from service v1.manager.authentication.AuthenticationService
 */
export const AuthenticationService: GenService<{
  /**
   * @generated from rpc v1.manager.authentication.AuthenticationService.Login
   */
  login: {
    methodKind: "unary";
    input: typeof LoginRequestSchema;
    output: typeof LoginResponseSchema;
  },
  /**
   * @generated from rpc v1.manager.authentication.AuthenticationService.Logout
   */
  logout: {
    methodKind: "unary";
    input: typeof LogoutRequestSchema;
    output: typeof LogoutResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_v1_manager_authentication_authentication, 0);

