// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: v1/manager/management/management.proto

package management

import (
	manager "github.com/megakuul/zen/pkg/api/v1/manager"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_v1_manager_management_management_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_manager_management_management_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_v1_manager_management_management_proto_rawDescGZIP(), []int{0}
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *manager.User          `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_v1_manager_management_management_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_manager_management_management_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_v1_manager_management_management_proto_rawDescGZIP(), []int{1}
}

func (x *GetResponse) GetUser() *manager.User {
	if x != nil {
		return x.User
	}
	return nil
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_v1_manager_management_management_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_manager_management_management_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_v1_manager_management_management_proto_rawDescGZIP(), []int{2}
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_v1_manager_management_management_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_manager_management_management_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_v1_manager_management_management_proto_rawDescGZIP(), []int{3}
}

var File_v1_manager_management_management_proto protoreflect.FileDescriptor

const file_v1_manager_management_management_proto_rawDesc = "" +
	"\n" +
	"&v1/manager/management/management.proto\x12\x15v1.manager.management\x1a\x15v1/manager/user.proto\"\f\n" +
	"\n" +
	"GetRequest\"3\n" +
	"\vGetResponse\x12$\n" +
	"\x04user\x18\x01 \x01(\v2\x10.v1.manager.UserR\x04user\"\x0f\n" +
	"\rDeleteRequest\"\x10\n" +
	"\x0eDeleteResponse2\xbc\x01\n" +
	"\x11ManagementService\x12N\n" +
	"\x03Get\x12!.v1.manager.management.GetRequest\x1a\".v1.manager.management.GetResponse\"\x00\x12W\n" +
	"\x06Delete\x12$.v1.manager.management.DeleteRequest\x1a%.v1.manager.management.DeleteResponse\"\x00B7Z5github.com/megakuul/zen/pkg/api/v1/manager/managementb\x06proto3"

var (
	file_v1_manager_management_management_proto_rawDescOnce sync.Once
	file_v1_manager_management_management_proto_rawDescData []byte
)

func file_v1_manager_management_management_proto_rawDescGZIP() []byte {
	file_v1_manager_management_management_proto_rawDescOnce.Do(func() {
		file_v1_manager_management_management_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_manager_management_management_proto_rawDesc), len(file_v1_manager_management_management_proto_rawDesc)))
	})
	return file_v1_manager_management_management_proto_rawDescData
}

var file_v1_manager_management_management_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_v1_manager_management_management_proto_goTypes = []any{
	(*GetRequest)(nil),     // 0: v1.manager.management.GetRequest
	(*GetResponse)(nil),    // 1: v1.manager.management.GetResponse
	(*DeleteRequest)(nil),  // 2: v1.manager.management.DeleteRequest
	(*DeleteResponse)(nil), // 3: v1.manager.management.DeleteResponse
	(*manager.User)(nil),   // 4: v1.manager.User
}
var file_v1_manager_management_management_proto_depIdxs = []int32{
	4, // 0: v1.manager.management.GetResponse.user:type_name -> v1.manager.User
	0, // 1: v1.manager.management.ManagementService.Get:input_type -> v1.manager.management.GetRequest
	2, // 2: v1.manager.management.ManagementService.Delete:input_type -> v1.manager.management.DeleteRequest
	1, // 3: v1.manager.management.ManagementService.Get:output_type -> v1.manager.management.GetResponse
	3, // 4: v1.manager.management.ManagementService.Delete:output_type -> v1.manager.management.DeleteResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_v1_manager_management_management_proto_init() }
func file_v1_manager_management_management_proto_init() {
	if File_v1_manager_management_management_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_manager_management_management_proto_rawDesc), len(file_v1_manager_management_management_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_manager_management_management_proto_goTypes,
		DependencyIndexes: file_v1_manager_management_management_proto_depIdxs,
		MessageInfos:      file_v1_manager_management_management_proto_msgTypes,
	}.Build()
	File_v1_manager_management_management_proto = out.File
	file_v1_manager_management_management_proto_goTypes = nil
	file_v1_manager_management_management_proto_depIdxs = nil
}
