// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: v1/manager/management/management.proto

package management

import (
	manager "github.com/megakuul/zen/pkg/api/v1/manager"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *manager.User          `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	CaptchaId     string                 `protobuf:"bytes,2,opt,name=captcha_id,json=captchaId,proto3" json:"captcha_id,omitempty"`
	CaptchaDigits string                 `protobuf:"bytes,3,opt,name=captcha_digits,json=captchaDigits,proto3" json:"captcha_digits,omitempty"`
	Verifier      *manager.Verifier      `protobuf:"bytes,4,opt,name=verifier,proto3" json:"verifier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_v1_manager_management_management_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_manager_management_management_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_v1_manager_management_management_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetUser() *manager.User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *RegisterRequest) GetCaptchaId() string {
	if x != nil {
		return x.CaptchaId
	}
	return ""
}

func (x *RegisterRequest) GetCaptchaDigits() string {
	if x != nil {
		return x.CaptchaDigits
	}
	return ""
}

func (x *RegisterRequest) GetVerifier() *manager.Verifier {
	if x != nil {
		return x.Verifier
	}
	return nil
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CaptchaId     string                 `protobuf:"bytes,1,opt,name=captcha_id,json=captchaId,proto3" json:"captcha_id,omitempty"`
	CaptchaBlob   []byte                 `protobuf:"bytes,2,opt,name=captcha_blob,json=captchaBlob,proto3" json:"captcha_blob,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_v1_manager_management_management_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_manager_management_management_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_v1_manager_management_management_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetCaptchaId() string {
	if x != nil {
		return x.CaptchaId
	}
	return ""
}

func (x *RegisterResponse) GetCaptchaBlob() []byte {
	if x != nil {
		return x.CaptchaBlob
	}
	return nil
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_v1_manager_management_management_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_manager_management_management_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_v1_manager_management_management_proto_rawDescGZIP(), []int{2}
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *manager.User          `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_v1_manager_management_management_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_manager_management_management_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_v1_manager_management_management_proto_rawDescGZIP(), []int{3}
}

func (x *GetResponse) GetUser() *manager.User {
	if x != nil {
		return x.User
	}
	return nil
}

type UpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *manager.User          `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_v1_manager_management_management_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_manager_management_management_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_v1_manager_management_management_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateRequest) GetUser() *manager.User {
	if x != nil {
		return x.User
	}
	return nil
}

type UpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	mi := &file_v1_manager_management_management_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_manager_management_management_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_v1_manager_management_management_proto_rawDescGZIP(), []int{5}
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Verifier      *manager.Verifier      `protobuf:"bytes,1,opt,name=verifier,proto3" json:"verifier,omitempty"` // bool delete_history = 2;
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_v1_manager_management_management_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_manager_management_management_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_v1_manager_management_management_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteRequest) GetVerifier() *manager.Verifier {
	if x != nil {
		return x.Verifier
	}
	return nil
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_v1_manager_management_management_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_manager_management_management_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_v1_manager_management_management_proto_rawDescGZIP(), []int{7}
}

var File_v1_manager_management_management_proto protoreflect.FileDescriptor

const file_v1_manager_management_management_proto_rawDesc = "" +
	"\n" +
	"&v1/manager/management/management.proto\x12\x15v1.manager.management\x1a\x15v1/manager/user.proto\x1a\x19v1/manager/verifier.proto\"\xaf\x01\n" +
	"\x0fRegisterRequest\x12$\n" +
	"\x04user\x18\x01 \x01(\v2\x10.v1.manager.UserR\x04user\x12\x1d\n" +
	"\n" +
	"captcha_id\x18\x02 \x01(\tR\tcaptchaId\x12%\n" +
	"\x0ecaptcha_digits\x18\x03 \x01(\tR\rcaptchaDigits\x120\n" +
	"\bverifier\x18\x04 \x01(\v2\x14.v1.manager.VerifierR\bverifier\"T\n" +
	"\x10RegisterResponse\x12\x1d\n" +
	"\n" +
	"captcha_id\x18\x01 \x01(\tR\tcaptchaId\x12!\n" +
	"\fcaptcha_blob\x18\x02 \x01(\fR\vcaptchaBlob\"\f\n" +
	"\n" +
	"GetRequest\"3\n" +
	"\vGetResponse\x12$\n" +
	"\x04user\x18\x01 \x01(\v2\x10.v1.manager.UserR\x04user\"5\n" +
	"\rUpdateRequest\x12$\n" +
	"\x04user\x18\x01 \x01(\v2\x10.v1.manager.UserR\x04user\"\x10\n" +
	"\x0eUpdateResponse\"A\n" +
	"\rDeleteRequest\x120\n" +
	"\bverifier\x18\x01 \x01(\v2\x14.v1.manager.VerifierR\bverifier\"\x10\n" +
	"\x0eDeleteResponse2\xf4\x02\n" +
	"\x11ManagementService\x12]\n" +
	"\bRegister\x12&.v1.manager.management.RegisterRequest\x1a'.v1.manager.management.RegisterResponse\"\x00\x12N\n" +
	"\x03Get\x12!.v1.manager.management.GetRequest\x1a\".v1.manager.management.GetResponse\"\x00\x12W\n" +
	"\x06Update\x12$.v1.manager.management.UpdateRequest\x1a%.v1.manager.management.UpdateResponse\"\x00\x12W\n" +
	"\x06Delete\x12$.v1.manager.management.DeleteRequest\x1a%.v1.manager.management.DeleteResponse\"\x00B7Z5github.com/megakuul/zen/pkg/api/v1/manager/managementb\x06proto3"

var (
	file_v1_manager_management_management_proto_rawDescOnce sync.Once
	file_v1_manager_management_management_proto_rawDescData []byte
)

func file_v1_manager_management_management_proto_rawDescGZIP() []byte {
	file_v1_manager_management_management_proto_rawDescOnce.Do(func() {
		file_v1_manager_management_management_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_manager_management_management_proto_rawDesc), len(file_v1_manager_management_management_proto_rawDesc)))
	})
	return file_v1_manager_management_management_proto_rawDescData
}

var file_v1_manager_management_management_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_v1_manager_management_management_proto_goTypes = []any{
	(*RegisterRequest)(nil),  // 0: v1.manager.management.RegisterRequest
	(*RegisterResponse)(nil), // 1: v1.manager.management.RegisterResponse
	(*GetRequest)(nil),       // 2: v1.manager.management.GetRequest
	(*GetResponse)(nil),      // 3: v1.manager.management.GetResponse
	(*UpdateRequest)(nil),    // 4: v1.manager.management.UpdateRequest
	(*UpdateResponse)(nil),   // 5: v1.manager.management.UpdateResponse
	(*DeleteRequest)(nil),    // 6: v1.manager.management.DeleteRequest
	(*DeleteResponse)(nil),   // 7: v1.manager.management.DeleteResponse
	(*manager.User)(nil),     // 8: v1.manager.User
	(*manager.Verifier)(nil), // 9: v1.manager.Verifier
}
var file_v1_manager_management_management_proto_depIdxs = []int32{
	8, // 0: v1.manager.management.RegisterRequest.user:type_name -> v1.manager.User
	9, // 1: v1.manager.management.RegisterRequest.verifier:type_name -> v1.manager.Verifier
	8, // 2: v1.manager.management.GetResponse.user:type_name -> v1.manager.User
	8, // 3: v1.manager.management.UpdateRequest.user:type_name -> v1.manager.User
	9, // 4: v1.manager.management.DeleteRequest.verifier:type_name -> v1.manager.Verifier
	0, // 5: v1.manager.management.ManagementService.Register:input_type -> v1.manager.management.RegisterRequest
	2, // 6: v1.manager.management.ManagementService.Get:input_type -> v1.manager.management.GetRequest
	4, // 7: v1.manager.management.ManagementService.Update:input_type -> v1.manager.management.UpdateRequest
	6, // 8: v1.manager.management.ManagementService.Delete:input_type -> v1.manager.management.DeleteRequest
	1, // 9: v1.manager.management.ManagementService.Register:output_type -> v1.manager.management.RegisterResponse
	3, // 10: v1.manager.management.ManagementService.Get:output_type -> v1.manager.management.GetResponse
	5, // 11: v1.manager.management.ManagementService.Update:output_type -> v1.manager.management.UpdateResponse
	7, // 12: v1.manager.management.ManagementService.Delete:output_type -> v1.manager.management.DeleteResponse
	9, // [9:13] is the sub-list for method output_type
	5, // [5:9] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_v1_manager_management_management_proto_init() }
func file_v1_manager_management_management_proto_init() {
	if File_v1_manager_management_management_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_manager_management_management_proto_rawDesc), len(file_v1_manager_management_management_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_manager_management_management_proto_goTypes,
		DependencyIndexes: file_v1_manager_management_management_proto_depIdxs,
		MessageInfos:      file_v1_manager_management_management_proto_msgTypes,
	}.Build()
	File_v1_manager_management_management_proto = out.File
	file_v1_manager_management_management_proto_goTypes = nil
	file_v1_manager_management_management_proto_depIdxs = nil
}
