// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: v1/manager/authentication/authentication.proto

package authentication

import (
	manager "github.com/megakuul/zen/pkg/api/v1/manager"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Verifier      *manager.Verifier      `protobuf:"bytes,1,opt,name=verifier,proto3" json:"verifier,omitempty"`
	AutoRefresh   bool                   `protobuf:"varint,2,opt,name=auto_refresh,json=autoRefresh,proto3" json:"auto_refresh,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_v1_manager_authentication_authentication_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_manager_authentication_authentication_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_v1_manager_authentication_authentication_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequest) GetVerifier() *manager.Verifier {
	if x != nil {
		return x.Verifier
	}
	return nil
}

func (x *LoginRequest) GetAutoRefresh() bool {
	if x != nil {
		return x.AutoRefresh
	}
	return false
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_v1_manager_authentication_authentication_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_manager_authentication_authentication_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_v1_manager_authentication_authentication_proto_rawDescGZIP(), []int{1}
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_v1_manager_authentication_authentication_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_manager_authentication_authentication_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_v1_manager_authentication_authentication_proto_rawDescGZIP(), []int{2}
}

type LogoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutResponse) Reset() {
	*x = LogoutResponse{}
	mi := &file_v1_manager_authentication_authentication_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutResponse) ProtoMessage() {}

func (x *LogoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_manager_authentication_authentication_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutResponse.ProtoReflect.Descriptor instead.
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return file_v1_manager_authentication_authentication_proto_rawDescGZIP(), []int{3}
}

var File_v1_manager_authentication_authentication_proto protoreflect.FileDescriptor

const file_v1_manager_authentication_authentication_proto_rawDesc = "" +
	"\n" +
	".v1/manager/authentication/authentication.proto\x12\x19v1.manager.authentication\x1a\x19v1/manager/verifier.proto\"c\n" +
	"\fLoginRequest\x120\n" +
	"\bverifier\x18\x01 \x01(\v2\x14.v1.manager.VerifierR\bverifier\x12!\n" +
	"\fauto_refresh\x18\x02 \x01(\bR\vautoRefresh\"%\n" +
	"\rLoginResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\x0f\n" +
	"\rLogoutRequest\"\x10\n" +
	"\x0eLogoutResponse2\xd6\x01\n" +
	"\x15AuthenticationService\x12\\\n" +
	"\x05Login\x12'.v1.manager.authentication.LoginRequest\x1a(.v1.manager.authentication.LoginResponse\"\x00\x12_\n" +
	"\x06Logout\x12(.v1.manager.authentication.LogoutRequest\x1a).v1.manager.authentication.LogoutResponse\"\x00B;Z9github.com/megakuul/zen/pkg/api/v1/manager/authenticationb\x06proto3"

var (
	file_v1_manager_authentication_authentication_proto_rawDescOnce sync.Once
	file_v1_manager_authentication_authentication_proto_rawDescData []byte
)

func file_v1_manager_authentication_authentication_proto_rawDescGZIP() []byte {
	file_v1_manager_authentication_authentication_proto_rawDescOnce.Do(func() {
		file_v1_manager_authentication_authentication_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_manager_authentication_authentication_proto_rawDesc), len(file_v1_manager_authentication_authentication_proto_rawDesc)))
	})
	return file_v1_manager_authentication_authentication_proto_rawDescData
}

var file_v1_manager_authentication_authentication_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_v1_manager_authentication_authentication_proto_goTypes = []any{
	(*LoginRequest)(nil),     // 0: v1.manager.authentication.LoginRequest
	(*LoginResponse)(nil),    // 1: v1.manager.authentication.LoginResponse
	(*LogoutRequest)(nil),    // 2: v1.manager.authentication.LogoutRequest
	(*LogoutResponse)(nil),   // 3: v1.manager.authentication.LogoutResponse
	(*manager.Verifier)(nil), // 4: v1.manager.Verifier
}
var file_v1_manager_authentication_authentication_proto_depIdxs = []int32{
	4, // 0: v1.manager.authentication.LoginRequest.verifier:type_name -> v1.manager.Verifier
	0, // 1: v1.manager.authentication.AuthenticationService.Login:input_type -> v1.manager.authentication.LoginRequest
	2, // 2: v1.manager.authentication.AuthenticationService.Logout:input_type -> v1.manager.authentication.LogoutRequest
	1, // 3: v1.manager.authentication.AuthenticationService.Login:output_type -> v1.manager.authentication.LoginResponse
	3, // 4: v1.manager.authentication.AuthenticationService.Logout:output_type -> v1.manager.authentication.LogoutResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_v1_manager_authentication_authentication_proto_init() }
func file_v1_manager_authentication_authentication_proto_init() {
	if File_v1_manager_authentication_authentication_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_manager_authentication_authentication_proto_rawDesc), len(file_v1_manager_authentication_authentication_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_manager_authentication_authentication_proto_goTypes,
		DependencyIndexes: file_v1_manager_authentication_authentication_proto_depIdxs,
		MessageInfos:      file_v1_manager_authentication_authentication_proto_msgTypes,
	}.Build()
	File_v1_manager_authentication_authentication_proto = out.File
	file_v1_manager_authentication_authentication_proto_goTypes = nil
	file_v1_manager_authentication_authentication_proto_depIdxs = nil
}
