// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: v1/manager/authentication/authentication.proto

package authentication

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Verifier      string                 `protobuf:"bytes,1,opt,name=verifier,proto3" json:"verifier,omitempty"`
	AutoRefresh   bool                   `protobuf:"varint,2,opt,name=auto_refresh,json=autoRefresh,proto3" json:"auto_refresh,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_v1_manager_authentication_authentication_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_manager_authentication_authentication_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_v1_manager_authentication_authentication_proto_rawDescGZIP(), []int{0}
}

func (x *GetRequest) GetVerifier() string {
	if x != nil {
		return x.Verifier
	}
	return ""
}

func (x *GetRequest) GetAutoRefresh() bool {
	if x != nil {
		return x.AutoRefresh
	}
	return false
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_v1_manager_authentication_authentication_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_manager_authentication_authentication_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_v1_manager_authentication_authentication_proto_rawDescGZIP(), []int{1}
}

func (x *GetResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type RevokeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeRequest) Reset() {
	*x = RevokeRequest{}
	mi := &file_v1_manager_authentication_authentication_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeRequest) ProtoMessage() {}

func (x *RevokeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_manager_authentication_authentication_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeRequest.ProtoReflect.Descriptor instead.
func (*RevokeRequest) Descriptor() ([]byte, []int) {
	return file_v1_manager_authentication_authentication_proto_rawDescGZIP(), []int{2}
}

type RevokeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeResponse) Reset() {
	*x = RevokeResponse{}
	mi := &file_v1_manager_authentication_authentication_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeResponse) ProtoMessage() {}

func (x *RevokeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_manager_authentication_authentication_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeResponse.ProtoReflect.Descriptor instead.
func (*RevokeResponse) Descriptor() ([]byte, []int) {
	return file_v1_manager_authentication_authentication_proto_rawDescGZIP(), []int{3}
}

var File_v1_manager_authentication_authentication_proto protoreflect.FileDescriptor

const file_v1_manager_authentication_authentication_proto_rawDesc = "" +
	"\n" +
	".v1/manager/authentication/authentication.proto\x12\x19v1.manager.authentication\"K\n" +
	"\n" +
	"GetRequest\x12\x1a\n" +
	"\bverifier\x18\x01 \x01(\tR\bverifier\x12!\n" +
	"\fauto_refresh\x18\x02 \x01(\bR\vautoRefresh\"#\n" +
	"\vGetResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\x0f\n" +
	"\rRevokeRequest\"\x10\n" +
	"\x0eRevokeResponse2\xd0\x01\n" +
	"\x15AuthenticationService\x12V\n" +
	"\x03Get\x12%.v1.manager.authentication.GetRequest\x1a&.v1.manager.authentication.GetResponse\"\x00\x12_\n" +
	"\x06Revoke\x12(.v1.manager.authentication.RevokeRequest\x1a).v1.manager.authentication.RevokeResponse\"\x00B;Z9github.com/megakuul/zen/pkg/api/v1/manager/authenticationb\x06proto3"

var (
	file_v1_manager_authentication_authentication_proto_rawDescOnce sync.Once
	file_v1_manager_authentication_authentication_proto_rawDescData []byte
)

func file_v1_manager_authentication_authentication_proto_rawDescGZIP() []byte {
	file_v1_manager_authentication_authentication_proto_rawDescOnce.Do(func() {
		file_v1_manager_authentication_authentication_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_manager_authentication_authentication_proto_rawDesc), len(file_v1_manager_authentication_authentication_proto_rawDesc)))
	})
	return file_v1_manager_authentication_authentication_proto_rawDescData
}

var file_v1_manager_authentication_authentication_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_v1_manager_authentication_authentication_proto_goTypes = []any{
	(*GetRequest)(nil),     // 0: v1.manager.authentication.GetRequest
	(*GetResponse)(nil),    // 1: v1.manager.authentication.GetResponse
	(*RevokeRequest)(nil),  // 2: v1.manager.authentication.RevokeRequest
	(*RevokeResponse)(nil), // 3: v1.manager.authentication.RevokeResponse
}
var file_v1_manager_authentication_authentication_proto_depIdxs = []int32{
	0, // 0: v1.manager.authentication.AuthenticationService.Get:input_type -> v1.manager.authentication.GetRequest
	2, // 1: v1.manager.authentication.AuthenticationService.Revoke:input_type -> v1.manager.authentication.RevokeRequest
	1, // 2: v1.manager.authentication.AuthenticationService.Get:output_type -> v1.manager.authentication.GetResponse
	3, // 3: v1.manager.authentication.AuthenticationService.Revoke:output_type -> v1.manager.authentication.RevokeResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_manager_authentication_authentication_proto_init() }
func file_v1_manager_authentication_authentication_proto_init() {
	if File_v1_manager_authentication_authentication_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_manager_authentication_authentication_proto_rawDesc), len(file_v1_manager_authentication_authentication_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_manager_authentication_authentication_proto_goTypes,
		DependencyIndexes: file_v1_manager_authentication_authentication_proto_depIdxs,
		MessageInfos:      file_v1_manager_authentication_authentication_proto_msgTypes,
	}.Build()
	File_v1_manager_authentication_authentication_proto = out.File
	file_v1_manager_authentication_authentication_proto_goTypes = nil
	file_v1_manager_authentication_authentication_proto_depIdxs = nil
}
