// @generated by protoc-gen-es v2.7.0 with parameter "target=ts"
// @generated from file v1/scheduler/event.proto (package v1.scheduler, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file v1/scheduler/event.proto.
 */
export const file_v1_scheduler_event: GenFile = /*@__PURE__*/
  fileDesc("Chh2MS9zY2hlZHVsZXIvZXZlbnQucHJvdG8SDHYxLnNjaGVkdWxlciKOAgoFRXZlbnQSCgoCaWQYASABKAkSJQoEdHlwZRgCIAEoDjIXLnYxLnNjaGVkdWxlci5FdmVudFR5cGUSDAoEbmFtZRgDIAEoCRISCgpzdGFydF90aW1lGAQgASgDEhEKCXN0b3BfdGltZRgFIAEoAxIYChB0aW1lcl9zdGFydF90aW1lGAYgASgDEhcKD3RpbWVyX3N0b3BfdGltZRgHIAEoAxIVCg1yYXRpbmdfY2hhbmdlGAggASgBEhgKEHJhdGluZ19hbGdvcml0aG0YCSABKAkSEQoJaW1tdXRhYmxlGAogASgIEhMKC2Rlc2NyaXB0aW9uGAsgASgJEhEKCW11c2ljX3VybBgMIAEoCSo/CglFdmVudFR5cGUSCQoFQ0hJTEwQABIJCgVQQVVTRRABEg0KCU1JTl9GT0NVUxACEg0KCU1BWF9GT0NVUxADQi5aLGdpdGh1Yi5jb20vbWVnYWt1dWwvemVuL3BrZy9hcGkvdjEvc2NoZWR1bGVyYgZwcm90bzM");

/**
 * @generated from message v1.scheduler.Event
 */
export type Event = Message<"v1.scheduler.Event"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: v1.scheduler.EventType type = 2;
   */
  type: EventType;

  /**
   * @generated from field: string name = 3;
   */
  name: string;

  /**
   * @generated from field: int64 start_time = 4;
   */
  startTime: bigint;

  /**
   * @generated from field: int64 stop_time = 5;
   */
  stopTime: bigint;

  /**
   * @generated from field: int64 timer_start_time = 6;
   */
  timerStartTime: bigint;

  /**
   * @generated from field: int64 timer_stop_time = 7;
   */
  timerStopTime: bigint;

  /**
   * @generated from field: double rating_change = 8;
   */
  ratingChange: number;

  /**
   * @generated from field: string rating_algorithm = 9;
   */
  ratingAlgorithm: string;

  /**
   * @generated from field: bool immutable = 10;
   */
  immutable: boolean;

  /**
   * @generated from field: string description = 11;
   */
  description: string;

  /**
   * @generated from field: string music_url = 12;
   */
  musicUrl: string;
};

/**
 * Describes the message v1.scheduler.Event.
 * Use `create(EventSchema)` to create a new message.
 */
export const EventSchema: GenMessage<Event> = /*@__PURE__*/
  messageDesc(file_v1_scheduler_event, 0);

/**
 * @generated from enum v1.scheduler.EventType
 */
export enum EventType {
  /**
   * @generated from enum value: CHILL = 0;
   */
  CHILL = 0,

  /**
   * @generated from enum value: PAUSE = 1;
   */
  PAUSE = 1,

  /**
   * @generated from enum value: MIN_FOCUS = 2;
   */
  MIN_FOCUS = 2,

  /**
   * @generated from enum value: MAX_FOCUS = 3;
   */
  MAX_FOCUS = 3,
}

/**
 * Describes the enum v1.scheduler.EventType.
 */
export const EventTypeSchema: GenEnum<EventType> = /*@__PURE__*/
  enumDesc(file_v1_scheduler_event, 0);

