// @generated by protoc-gen-es v2.7.0 with parameter "target=ts"
// @generated from file v1/scheduler/event.proto (package v1.scheduler, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file v1/scheduler/event.proto.
 */
export const file_v1_scheduler_event: GenFile = /*@__PURE__*/
  fileDesc("Chh2MS9zY2hlZHVsZXIvZXZlbnQucHJvdG8SDHYxLnNjaGVkdWxlciKOAgoFRXZlbnQSCgoCaWQYASABKAkSJQoEdHlwZRgCIAEoDjIXLnYxLnNjaGVkdWxlci5FdmVudFR5cGUSDAoEbmFtZRgDIAEoCRISCgpzdGFydF90aW1lGAQgASgDEhEKCXN0b3BfdGltZRgFIAEoAxIYChB0aW1lcl9zdGFydF90aW1lGAYgASgDEhcKD3RpbWVyX3N0b3BfdGltZRgHIAEoAxIVCg1yYXRpbmdfY2hhbmdlGAggASgBEhgKEHJhdGluZ19hbGdvcml0aG0YCSABKAkSEQoJaW1tdXRhYmxlGAogASgIEhMKC2Rlc2NyaXB0aW9uGAsgASgJEhEKCW11c2ljX3VybBgMIAEoCSpQCglFdmVudFR5cGUSDQoJQVVUT1BJTE9UEAASCwoHQVVESVRPUhABEgwKCEVYUExPUkVSEAISDAoIRVhFQ1VUT1IQAxILCgdXQVJSSU9SEARCLlosZ2l0aHViLmNvbS9tZWdha3V1bC96ZW4vcGtnL2FwaS92MS9zY2hlZHVsZXJiBnByb3RvMw");

/**
 * @generated from message v1.scheduler.Event
 */
export type Event = Message<"v1.scheduler.Event"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: v1.scheduler.EventType type = 2;
   */
  type: EventType;

  /**
   * @generated from field: string name = 3;
   */
  name: string;

  /**
   * @generated from field: int64 start_time = 4;
   */
  startTime: bigint;

  /**
   * @generated from field: int64 stop_time = 5;
   */
  stopTime: bigint;

  /**
   * @generated from field: int64 timer_start_time = 6;
   */
  timerStartTime: bigint;

  /**
   * @generated from field: int64 timer_stop_time = 7;
   */
  timerStopTime: bigint;

  /**
   * @generated from field: double rating_change = 8;
   */
  ratingChange: number;

  /**
   * @generated from field: string rating_algorithm = 9;
   */
  ratingAlgorithm: string;

  /**
   * @generated from field: bool immutable = 10;
   */
  immutable: boolean;

  /**
   * @generated from field: string description = 11;
   */
  description: string;

  /**
   * @generated from field: string music_url = 12;
   */
  musicUrl: string;
};

/**
 * Describes the message v1.scheduler.Event.
 * Use `create(EventSchema)` to create a new message.
 */
export const EventSchema: GenMessage<Event> = /*@__PURE__*/
  messageDesc(file_v1_scheduler_event, 0);

/**
 * @generated from enum v1.scheduler.EventType
 */
export enum EventType {
  /**
   * AUTOPILOT is useful for basic repetitive tasks where you do not need focus
   * trigger: defaults whenever you throw focus (e.g. looking around, thinking about different things).
   * driver: serotonin (requires l-tryptophan)
   *
   * @generated from enum value: AUTOPILOT = 0;
   */
  AUTOPILOT = 0,

  /**
   * AUDITOR is useful for short and strong focus with complete awareness
   * trigger: stress (task must be finished in 30 minutes with high stakes) -> battery hack
   * driver: noradrenaline (requires l-tyrosin)
   * reset: requires nsdr reset to switch to other modes (1-4).
   *
   * @generated from enum value: AUDITOR = 1;
   */
  AUDITOR = 1,

  /**
   * EXPLORER (learning) is useful for tasks you don't know how to approach (learning things)
   * trigger: stare at a point for 30 seconds without blinking (triggers acetylcholine)
   * driver: acetylcholine (requires cholin (alpha-gpc)) and noradrenaline (requires l-tyrosin)
   * reset: requires nsdr reset to switch to other modes (1-4).
   *
   * @generated from enum value: EXPLORER = 2;
   */
  EXPLORER = 2,

  /**
   * EXECUTOR (flow) is useful for tasks you already know how to approach exactly but with 5-10x speed
   * trigger: shut all external factors immediately and start working on exactly defined tasks.
   * driver: noradrenaline and dopamine (requires l-tyrosin)
   * reset: requires nsdr reset to switch to other modes (1-4).
   *
   * @generated from enum value: EXECUTOR = 3;
   */
  EXECUTOR = 3,

  /**
   * WARRIOR is useful for tasks you need physical and mental power (sports)
   * trigger: starting intensive workout automatically triggers this
   * driver: adrenalin and endorphin (requires l-tyrosin)
   * note: requires carbs for energy and BCAA amino acids to counter the insulin flush from those carbs (to avoid l-tryptophan entrance)
   * reset: requires nsdr reset to switch to other modes (1-4).
   *
   * @generated from enum value: WARRIOR = 4;
   */
  WARRIOR = 4,
}

/**
 * Describes the enum v1.scheduler.EventType.
 */
export const EventTypeSchema: GenEnum<EventType> = /*@__PURE__*/
  enumDesc(file_v1_scheduler_event, 0);

