// @generated by protoc-gen-es v2.7.0 with parameter "target=ts"
// @generated from file v1/scheduler/planner.proto (package v1.scheduler, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Event } from "./event_pb";
import { file_v1_scheduler_event } from "./event_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file v1/scheduler/planner.proto.
 */
export const file_v1_scheduler_planner: GenFile = /*@__PURE__*/
  fileDesc("Chp2MS9zY2hlZHVsZXIvcGxhbm5lci5wcm90bxIMdjEuc2NoZWR1bGVyIhkKCkdldFJlcXVlc3QSCwoDZGF5GAEgASgDIjIKC0dldFJlc3BvbnNlEiMKBmV2ZW50cxgBIAMoCzITLnYxLnNjaGVkdWxlci5FdmVudCIzCg1VcHNlcnRSZXF1ZXN0EiIKBWV2ZW50GAEgASgLMhMudjEuc2NoZWR1bGVyLkV2ZW50IhAKDlVwc2VydFJlc3BvbnNlIhsKDURlbGV0ZVJlcXVlc3QSCgoCaWQYASABKAkiEAoORGVsZXRlUmVzcG9uc2Uy3AEKDlBsYW5uZXJTZXJ2aWNlEjwKA0dldBIYLnYxLnNjaGVkdWxlci5HZXRSZXF1ZXN0GhkudjEuc2NoZWR1bGVyLkdldFJlc3BvbnNlIgASRQoGVXBzZXJ0EhsudjEuc2NoZWR1bGVyLlVwc2VydFJlcXVlc3QaHC52MS5zY2hlZHVsZXIuVXBzZXJ0UmVzcG9uc2UiABJFCgZEZWxldGUSGy52MS5zY2hlZHVsZXIuRGVsZXRlUmVxdWVzdBocLnYxLnNjaGVkdWxlci5EZWxldGVSZXNwb25zZSIAQi5aLGdpdGh1Yi5jb20vbWVnYWt1dWwvemVuL3BrZy9hcGkvdjEvc2NoZWR1bGVyYgZwcm90bzM", [file_v1_scheduler_event]);

/**
 * @generated from message v1.scheduler.GetRequest
 */
export type GetRequest = Message<"v1.scheduler.GetRequest"> & {
  /**
   * @generated from field: int64 day = 1;
   */
  day: bigint;
};

/**
 * Describes the message v1.scheduler.GetRequest.
 * Use `create(GetRequestSchema)` to create a new message.
 */
export const GetRequestSchema: GenMessage<GetRequest> = /*@__PURE__*/
  messageDesc(file_v1_scheduler_planner, 0);

/**
 * @generated from message v1.scheduler.GetResponse
 */
export type GetResponse = Message<"v1.scheduler.GetResponse"> & {
  /**
   * @generated from field: repeated v1.scheduler.Event events = 1;
   */
  events: Event[];
};

/**
 * Describes the message v1.scheduler.GetResponse.
 * Use `create(GetResponseSchema)` to create a new message.
 */
export const GetResponseSchema: GenMessage<GetResponse> = /*@__PURE__*/
  messageDesc(file_v1_scheduler_planner, 1);

/**
 * @generated from message v1.scheduler.UpsertRequest
 */
export type UpsertRequest = Message<"v1.scheduler.UpsertRequest"> & {
  /**
   * @generated from field: v1.scheduler.Event event = 1;
   */
  event?: Event;
};

/**
 * Describes the message v1.scheduler.UpsertRequest.
 * Use `create(UpsertRequestSchema)` to create a new message.
 */
export const UpsertRequestSchema: GenMessage<UpsertRequest> = /*@__PURE__*/
  messageDesc(file_v1_scheduler_planner, 2);

/**
 * @generated from message v1.scheduler.UpsertResponse
 */
export type UpsertResponse = Message<"v1.scheduler.UpsertResponse"> & {
};

/**
 * Describes the message v1.scheduler.UpsertResponse.
 * Use `create(UpsertResponseSchema)` to create a new message.
 */
export const UpsertResponseSchema: GenMessage<UpsertResponse> = /*@__PURE__*/
  messageDesc(file_v1_scheduler_planner, 3);

/**
 * @generated from message v1.scheduler.DeleteRequest
 */
export type DeleteRequest = Message<"v1.scheduler.DeleteRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message v1.scheduler.DeleteRequest.
 * Use `create(DeleteRequestSchema)` to create a new message.
 */
export const DeleteRequestSchema: GenMessage<DeleteRequest> = /*@__PURE__*/
  messageDesc(file_v1_scheduler_planner, 4);

/**
 * @generated from message v1.scheduler.DeleteResponse
 */
export type DeleteResponse = Message<"v1.scheduler.DeleteResponse"> & {
};

/**
 * Describes the message v1.scheduler.DeleteResponse.
 * Use `create(DeleteResponseSchema)` to create a new message.
 */
export const DeleteResponseSchema: GenMessage<DeleteResponse> = /*@__PURE__*/
  messageDesc(file_v1_scheduler_planner, 5);

/**
 * @generated from service v1.scheduler.PlannerService
 */
export const PlannerService: GenService<{
  /**
   * @generated from rpc v1.scheduler.PlannerService.Get
   */
  get: {
    methodKind: "unary";
    input: typeof GetRequestSchema;
    output: typeof GetResponseSchema;
  },
  /**
   * @generated from rpc v1.scheduler.PlannerService.Upsert
   */
  upsert: {
    methodKind: "unary";
    input: typeof UpsertRequestSchema;
    output: typeof UpsertResponseSchema;
  },
  /**
   * @generated from rpc v1.scheduler.PlannerService.Delete
   */
  delete: {
    methodKind: "unary";
    input: typeof DeleteRequestSchema;
    output: typeof DeleteResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_v1_scheduler_planner, 0);

