// @generated by protoc-gen-es v2.7.0 with parameter "target=ts"
// @generated from file v1/scheduler/timer.proto (package v1.scheduler, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_v1_scheduler_event } from "./event_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file v1/scheduler/timer.proto.
 */
export const file_v1_scheduler_timer: GenFile = /*@__PURE__*/
  fileDesc("Chh2MS9zY2hlZHVsZXIvdGltZXIucHJvdG8SDHYxLnNjaGVkdWxlciIuCgxTdGFydFJlcXVlc3QSCgoCaWQYASABKAkSEgoKc3RhcnRfdGltZRgCIAEoAyIPCg1TdGFydFJlc3BvbnNlIiwKC1N0b3BSZXF1ZXN0EgoKAmlkGAEgASgJEhEKCXN0b3BfdGltZRgCIAEoAyIOCgxTdG9wUmVzcG9uc2UykwEKDFRpbWVyU2VydmljZRJCCgVTdGFydBIaLnYxLnNjaGVkdWxlci5TdGFydFJlcXVlc3QaGy52MS5zY2hlZHVsZXIuU3RhcnRSZXNwb25zZSIAEj8KBFN0b3ASGS52MS5zY2hlZHVsZXIuU3RvcFJlcXVlc3QaGi52MS5zY2hlZHVsZXIuU3RvcFJlc3BvbnNlIgBCLlosZ2l0aHViLmNvbS9tZWdha3V1bC96ZW4vcGtnL2FwaS92MS9zY2hlZHVsZXJiBnByb3RvMw", [file_v1_scheduler_event]);

/**
 * @generated from message v1.scheduler.StartRequest
 */
export type StartRequest = Message<"v1.scheduler.StartRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: int64 start_time = 2;
   */
  startTime: bigint;
};

/**
 * Describes the message v1.scheduler.StartRequest.
 * Use `create(StartRequestSchema)` to create a new message.
 */
export const StartRequestSchema: GenMessage<StartRequest> = /*@__PURE__*/
  messageDesc(file_v1_scheduler_timer, 0);

/**
 * @generated from message v1.scheduler.StartResponse
 */
export type StartResponse = Message<"v1.scheduler.StartResponse"> & {
};

/**
 * Describes the message v1.scheduler.StartResponse.
 * Use `create(StartResponseSchema)` to create a new message.
 */
export const StartResponseSchema: GenMessage<StartResponse> = /*@__PURE__*/
  messageDesc(file_v1_scheduler_timer, 1);

/**
 * @generated from message v1.scheduler.StopRequest
 */
export type StopRequest = Message<"v1.scheduler.StopRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: int64 stop_time = 2;
   */
  stopTime: bigint;
};

/**
 * Describes the message v1.scheduler.StopRequest.
 * Use `create(StopRequestSchema)` to create a new message.
 */
export const StopRequestSchema: GenMessage<StopRequest> = /*@__PURE__*/
  messageDesc(file_v1_scheduler_timer, 2);

/**
 * @generated from message v1.scheduler.StopResponse
 */
export type StopResponse = Message<"v1.scheduler.StopResponse"> & {
};

/**
 * Describes the message v1.scheduler.StopResponse.
 * Use `create(StopResponseSchema)` to create a new message.
 */
export const StopResponseSchema: GenMessage<StopResponse> = /*@__PURE__*/
  messageDesc(file_v1_scheduler_timer, 3);

/**
 * @generated from service v1.scheduler.TimerService
 */
export const TimerService: GenService<{
  /**
   * @generated from rpc v1.scheduler.TimerService.Start
   */
  start: {
    methodKind: "unary";
    input: typeof StartRequestSchema;
    output: typeof StartResponseSchema;
  },
  /**
   * @generated from rpc v1.scheduler.TimerService.Stop
   */
  stop: {
    methodKind: "unary";
    input: typeof StopRequestSchema;
    output: typeof StopResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_v1_scheduler_timer, 0);

