// @generated by protoc-gen-es v2.7.0 with parameter "target=ts"
// @generated from file v1/manager/user.proto (package v1.manager, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file v1/manager/user.proto.
 */
export const file_v1_manager_user: GenFile = /*@__PURE__*/
  fileDesc("ChV2MS9tYW5hZ2VyL3VzZXIucHJvdG8SCnYxLm1hbmFnZXIikAEKBFVzZXISCgoCaWQYASABKAkSEAoIdXNlcm5hbWUYAiABKAkSEwoLZGVzY3JpcHRpb24YAyABKAkSDQoFZW1haWwYBCABKAkSEwoLbGVhZGVyYm9hcmQYBSABKAgSEgoKY3JlYXRlZF9hdBgGIAEoAxIOCgZzdHJlYWsYByABKAMSDQoFc2NvcmUYCCABKAFCLFoqZ2l0aHViLmNvbS9tZWdha3V1bC96ZW4vcGtnL2FwaS92MS9tYW5hZ2VyYgZwcm90bzM");

/**
 * @generated from message v1.manager.User
 */
export type User = Message<"v1.manager.User"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string username = 2;
   */
  username: string;

  /**
   * @generated from field: string description = 3;
   */
  description: string;

  /**
   * @generated from field: string email = 4;
   */
  email: string;

  /**
   * @generated from field: bool leaderboard = 5;
   */
  leaderboard: boolean;

  /**
   * @generated from field: int64 created_at = 6;
   */
  createdAt: bigint;

  /**
   * @generated from field: int64 streak = 7;
   */
  streak: bigint;

  /**
   * @generated from field: double score = 8;
   */
  score: number;
};

/**
 * Describes the message v1.manager.User.
 * Use `create(UserSchema)` to create a new message.
 */
export const UserSchema: GenMessage<User> = /*@__PURE__*/
  messageDesc(file_v1_manager_user, 0);

