// @generated by protoc-gen-es v2.7.0 with parameter "target=ts"
// @generated from file v1/manager/verifier.proto (package v1.manager, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file v1/manager/verifier.proto.
 */
export const file_v1_manager_verifier: GenFile = /*@__PURE__*/
  fileDesc("Chl2MS9tYW5hZ2VyL3ZlcmlmaWVyLnByb3RvEgp2MS5tYW5hZ2VyIlEKCFZlcmlmaWVyEigKBXN0YWdlGAEgASgOMhkudjEubWFuYWdlci5WZXJpZmllclN0YWdlEg0KBWVtYWlsGAIgASgJEgwKBGNvZGUYAyABKAkqQgoNVmVyaWZpZXJTdGFnZRIYChRWRVJJRklFUl9TVEFHRV9FTUFJTBAAEhcKE1ZFUklGSUVSX1NUQUdFX0NPREUQAUIsWipnaXRodWIuY29tL21lZ2FrdXVsL3plbi9wa2cvYXBpL3YxL21hbmFnZXJiBnByb3RvMw");

/**
 * @generated from message v1.manager.Verifier
 */
export type Verifier = Message<"v1.manager.Verifier"> & {
  /**
   * @generated from field: v1.manager.VerifierStage stage = 1;
   */
  stage: VerifierStage;

  /**
   * @generated from field: string email = 2;
   */
  email: string;

  /**
   * @generated from field: string code = 3;
   */
  code: string;
};

/**
 * Describes the message v1.manager.Verifier.
 * Use `create(VerifierSchema)` to create a new message.
 */
export const VerifierSchema: GenMessage<Verifier> = /*@__PURE__*/
  messageDesc(file_v1_manager_verifier, 0);

/**
 * @generated from enum v1.manager.VerifierStage
 */
export enum VerifierStage {
  /**
   * @generated from enum value: VERIFIER_STAGE_EMAIL = 0;
   */
  EMAIL = 0,

  /**
   * @generated from enum value: VERIFIER_STAGE_CODE = 1;
   */
  CODE = 1,
}

/**
 * Describes the enum v1.manager.VerifierStage.
 */
export const VerifierStageSchema: GenEnum<VerifierStage> = /*@__PURE__*/
  enumDesc(file_v1_manager_verifier, 0);

