// @generated by protoc-gen-es v2.7.0 with parameter "target=ts"
// @generated from file v1/manager/management/management.proto (package v1.manager.management, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { User } from "../user_pb";
import { file_v1_manager_user } from "../user_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file v1/manager/management/management.proto.
 */
export const file_v1_manager_management_management: GenFile = /*@__PURE__*/
  fileDesc("CiZ2MS9tYW5hZ2VyL21hbmFnZW1lbnQvbWFuYWdlbWVudC5wcm90bxIVdjEubWFuYWdlci5tYW5hZ2VtZW50IgwKCkdldFJlcXVlc3QiLQoLR2V0UmVzcG9uc2USHgoEdXNlchgBIAEoCzIQLnYxLm1hbmFnZXIuVXNlciIPCg1EZWxldGVSZXF1ZXN0IhAKDkRlbGV0ZVJlc3BvbnNlMrwBChFNYW5hZ2VtZW50U2VydmljZRJOCgNHZXQSIS52MS5tYW5hZ2VyLm1hbmFnZW1lbnQuR2V0UmVxdWVzdBoiLnYxLm1hbmFnZXIubWFuYWdlbWVudC5HZXRSZXNwb25zZSIAElcKBkRlbGV0ZRIkLnYxLm1hbmFnZXIubWFuYWdlbWVudC5EZWxldGVSZXF1ZXN0GiUudjEubWFuYWdlci5tYW5hZ2VtZW50LkRlbGV0ZVJlc3BvbnNlIgBCN1o1Z2l0aHViLmNvbS9tZWdha3V1bC96ZW4vcGtnL2FwaS92MS9tYW5hZ2VyL21hbmFnZW1lbnRiBnByb3RvMw", [file_v1_manager_user]);

/**
 * @generated from message v1.manager.management.GetRequest
 */
export type GetRequest = Message<"v1.manager.management.GetRequest"> & {
};

/**
 * Describes the message v1.manager.management.GetRequest.
 * Use `create(GetRequestSchema)` to create a new message.
 */
export const GetRequestSchema: GenMessage<GetRequest> = /*@__PURE__*/
  messageDesc(file_v1_manager_management_management, 0);

/**
 * @generated from message v1.manager.management.GetResponse
 */
export type GetResponse = Message<"v1.manager.management.GetResponse"> & {
  /**
   * @generated from field: v1.manager.User user = 1;
   */
  user?: User;
};

/**
 * Describes the message v1.manager.management.GetResponse.
 * Use `create(GetResponseSchema)` to create a new message.
 */
export const GetResponseSchema: GenMessage<GetResponse> = /*@__PURE__*/
  messageDesc(file_v1_manager_management_management, 1);

/**
 * @generated from message v1.manager.management.DeleteRequest
 */
export type DeleteRequest = Message<"v1.manager.management.DeleteRequest"> & {
};

/**
 * Describes the message v1.manager.management.DeleteRequest.
 * Use `create(DeleteRequestSchema)` to create a new message.
 */
export const DeleteRequestSchema: GenMessage<DeleteRequest> = /*@__PURE__*/
  messageDesc(file_v1_manager_management_management, 2);

/**
 * @generated from message v1.manager.management.DeleteResponse
 */
export type DeleteResponse = Message<"v1.manager.management.DeleteResponse"> & {
};

/**
 * Describes the message v1.manager.management.DeleteResponse.
 * Use `create(DeleteResponseSchema)` to create a new message.
 */
export const DeleteResponseSchema: GenMessage<DeleteResponse> = /*@__PURE__*/
  messageDesc(file_v1_manager_management_management, 3);

/**
 * @generated from service v1.manager.management.ManagementService
 */
export const ManagementService: GenService<{
  /**
   * @generated from rpc v1.manager.management.ManagementService.Get
   */
  get: {
    methodKind: "unary";
    input: typeof GetRequestSchema;
    output: typeof GetResponseSchema;
  },
  /**
   * @generated from rpc v1.manager.management.ManagementService.Delete
   */
  delete: {
    methodKind: "unary";
    input: typeof DeleteRequestSchema;
    output: typeof DeleteResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_v1_manager_management_management, 0);

