// @generated by protoc-gen-es v2.7.0 with parameter "target=ts"
// @generated from file v1/manager/management/management.proto (package v1.manager.management, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { User } from "../user_pb";
import { file_v1_manager_user } from "../user_pb";
import type { Verifier } from "../verifier_pb";
import { file_v1_manager_verifier } from "../verifier_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file v1/manager/management/management.proto.
 */
export const file_v1_manager_management_management: GenFile = /*@__PURE__*/
  fileDesc("CiZ2MS9tYW5hZ2VyL21hbmFnZW1lbnQvbWFuYWdlbWVudC5wcm90bxIVdjEubWFuYWdlci5tYW5hZ2VtZW50IoUBCg9SZWdpc3RlclJlcXVlc3QSHgoEdXNlchgBIAEoCzIQLnYxLm1hbmFnZXIuVXNlchISCgpjYXB0Y2hhX2lkGAIgASgJEhYKDmNhcHRjaGFfZGlnaXRzGAMgASgJEiYKCHZlcmlmaWVyGAQgASgLMhQudjEubWFuYWdlci5WZXJpZmllciI8ChBSZWdpc3RlclJlc3BvbnNlEhIKCmNhcHRjaGFfaWQYASABKAkSFAoMY2FwdGNoYV9ibG9iGAIgASgMIgwKCkdldFJlcXVlc3QiLQoLR2V0UmVzcG9uc2USHgoEdXNlchgBIAEoCzIQLnYxLm1hbmFnZXIuVXNlciIvCg1VcGRhdGVSZXF1ZXN0Eh4KBHVzZXIYASABKAsyEC52MS5tYW5hZ2VyLlVzZXIiEAoOVXBkYXRlUmVzcG9uc2UiNwoNRGVsZXRlUmVxdWVzdBImCgh2ZXJpZmllchgBIAEoCzIULnYxLm1hbmFnZXIuVmVyaWZpZXIiEAoORGVsZXRlUmVzcG9uc2Uy9AIKEU1hbmFnZW1lbnRTZXJ2aWNlEl0KCFJlZ2lzdGVyEiYudjEubWFuYWdlci5tYW5hZ2VtZW50LlJlZ2lzdGVyUmVxdWVzdBonLnYxLm1hbmFnZXIubWFuYWdlbWVudC5SZWdpc3RlclJlc3BvbnNlIgASTgoDR2V0EiEudjEubWFuYWdlci5tYW5hZ2VtZW50LkdldFJlcXVlc3QaIi52MS5tYW5hZ2VyLm1hbmFnZW1lbnQuR2V0UmVzcG9uc2UiABJXCgZVcGRhdGUSJC52MS5tYW5hZ2VyLm1hbmFnZW1lbnQuVXBkYXRlUmVxdWVzdBolLnYxLm1hbmFnZXIubWFuYWdlbWVudC5VcGRhdGVSZXNwb25zZSIAElcKBkRlbGV0ZRIkLnYxLm1hbmFnZXIubWFuYWdlbWVudC5EZWxldGVSZXF1ZXN0GiUudjEubWFuYWdlci5tYW5hZ2VtZW50LkRlbGV0ZVJlc3BvbnNlIgBCN1o1Z2l0aHViLmNvbS9tZWdha3V1bC96ZW4vcGtnL2FwaS92MS9tYW5hZ2VyL21hbmFnZW1lbnRiBnByb3RvMw", [file_v1_manager_user, file_v1_manager_verifier]);

/**
 * @generated from message v1.manager.management.RegisterRequest
 */
export type RegisterRequest = Message<"v1.manager.management.RegisterRequest"> & {
  /**
   * @generated from field: v1.manager.User user = 1;
   */
  user?: User;

  /**
   * @generated from field: string captcha_id = 2;
   */
  captchaId: string;

  /**
   * @generated from field: string captcha_digits = 3;
   */
  captchaDigits: string;

  /**
   * @generated from field: v1.manager.Verifier verifier = 4;
   */
  verifier?: Verifier;
};

/**
 * Describes the message v1.manager.management.RegisterRequest.
 * Use `create(RegisterRequestSchema)` to create a new message.
 */
export const RegisterRequestSchema: GenMessage<RegisterRequest> = /*@__PURE__*/
  messageDesc(file_v1_manager_management_management, 0);

/**
 * @generated from message v1.manager.management.RegisterResponse
 */
export type RegisterResponse = Message<"v1.manager.management.RegisterResponse"> & {
  /**
   * @generated from field: string captcha_id = 1;
   */
  captchaId: string;

  /**
   * @generated from field: bytes captcha_blob = 2;
   */
  captchaBlob: Uint8Array;
};

/**
 * Describes the message v1.manager.management.RegisterResponse.
 * Use `create(RegisterResponseSchema)` to create a new message.
 */
export const RegisterResponseSchema: GenMessage<RegisterResponse> = /*@__PURE__*/
  messageDesc(file_v1_manager_management_management, 1);

/**
 * @generated from message v1.manager.management.GetRequest
 */
export type GetRequest = Message<"v1.manager.management.GetRequest"> & {
};

/**
 * Describes the message v1.manager.management.GetRequest.
 * Use `create(GetRequestSchema)` to create a new message.
 */
export const GetRequestSchema: GenMessage<GetRequest> = /*@__PURE__*/
  messageDesc(file_v1_manager_management_management, 2);

/**
 * @generated from message v1.manager.management.GetResponse
 */
export type GetResponse = Message<"v1.manager.management.GetResponse"> & {
  /**
   * @generated from field: v1.manager.User user = 1;
   */
  user?: User;
};

/**
 * Describes the message v1.manager.management.GetResponse.
 * Use `create(GetResponseSchema)` to create a new message.
 */
export const GetResponseSchema: GenMessage<GetResponse> = /*@__PURE__*/
  messageDesc(file_v1_manager_management_management, 3);

/**
 * @generated from message v1.manager.management.UpdateRequest
 */
export type UpdateRequest = Message<"v1.manager.management.UpdateRequest"> & {
  /**
   * @generated from field: v1.manager.User user = 1;
   */
  user?: User;
};

/**
 * Describes the message v1.manager.management.UpdateRequest.
 * Use `create(UpdateRequestSchema)` to create a new message.
 */
export const UpdateRequestSchema: GenMessage<UpdateRequest> = /*@__PURE__*/
  messageDesc(file_v1_manager_management_management, 4);

/**
 * @generated from message v1.manager.management.UpdateResponse
 */
export type UpdateResponse = Message<"v1.manager.management.UpdateResponse"> & {
};

/**
 * Describes the message v1.manager.management.UpdateResponse.
 * Use `create(UpdateResponseSchema)` to create a new message.
 */
export const UpdateResponseSchema: GenMessage<UpdateResponse> = /*@__PURE__*/
  messageDesc(file_v1_manager_management_management, 5);

/**
 * @generated from message v1.manager.management.DeleteRequest
 */
export type DeleteRequest = Message<"v1.manager.management.DeleteRequest"> & {
  /**
   * bool delete_history = 2;
   *
   * @generated from field: v1.manager.Verifier verifier = 1;
   */
  verifier?: Verifier;
};

/**
 * Describes the message v1.manager.management.DeleteRequest.
 * Use `create(DeleteRequestSchema)` to create a new message.
 */
export const DeleteRequestSchema: GenMessage<DeleteRequest> = /*@__PURE__*/
  messageDesc(file_v1_manager_management_management, 6);

/**
 * @generated from message v1.manager.management.DeleteResponse
 */
export type DeleteResponse = Message<"v1.manager.management.DeleteResponse"> & {
};

/**
 * Describes the message v1.manager.management.DeleteResponse.
 * Use `create(DeleteResponseSchema)` to create a new message.
 */
export const DeleteResponseSchema: GenMessage<DeleteResponse> = /*@__PURE__*/
  messageDesc(file_v1_manager_management_management, 7);

/**
 * @generated from service v1.manager.management.ManagementService
 */
export const ManagementService: GenService<{
  /**
   * @generated from rpc v1.manager.management.ManagementService.Register
   */
  register: {
    methodKind: "unary";
    input: typeof RegisterRequestSchema;
    output: typeof RegisterResponseSchema;
  },
  /**
   * @generated from rpc v1.manager.management.ManagementService.Get
   */
  get: {
    methodKind: "unary";
    input: typeof GetRequestSchema;
    output: typeof GetResponseSchema;
  },
  /**
   * @generated from rpc v1.manager.management.ManagementService.Update
   */
  update: {
    methodKind: "unary";
    input: typeof UpdateRequestSchema;
    output: typeof UpdateResponseSchema;
  },
  /**
   * @generated from rpc v1.manager.management.ManagementService.Delete
   */
  delete: {
    methodKind: "unary";
    input: typeof DeleteRequestSchema;
    output: typeof DeleteResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_v1_manager_management_management, 0);

