// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: v1/manager/user.proto

package manager

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Leaderboard   bool                   `protobuf:"varint,5,opt,name=leaderboard,proto3" json:"leaderboard,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Streak        int64                  `protobuf:"varint,7,opt,name=streak,proto3" json:"streak,omitempty"`
	Score         float64                `protobuf:"fixed64,8,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_v1_manager_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_v1_manager_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_v1_manager_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetLeaderboard() bool {
	if x != nil {
		return x.Leaderboard
	}
	return false
}

func (x *User) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *User) GetStreak() int64 {
	if x != nil {
		return x.Streak
	}
	return 0
}

func (x *User) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

var File_v1_manager_user_proto protoreflect.FileDescriptor

const file_v1_manager_user_proto_rawDesc = "" +
	"\n" +
	"\x15v1/manager/user.proto\x12\n" +
	"v1.manager\"\xd9\x01\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12 \n" +
	"\vleaderboard\x18\x05 \x01(\bR\vleaderboard\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\x12\x16\n" +
	"\x06streak\x18\a \x01(\x03R\x06streak\x12\x14\n" +
	"\x05score\x18\b \x01(\x01R\x05scoreB,Z*github.com/megakuul/zen/pkg/api/v1/managerb\x06proto3"

var (
	file_v1_manager_user_proto_rawDescOnce sync.Once
	file_v1_manager_user_proto_rawDescData []byte
)

func file_v1_manager_user_proto_rawDescGZIP() []byte {
	file_v1_manager_user_proto_rawDescOnce.Do(func() {
		file_v1_manager_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_manager_user_proto_rawDesc), len(file_v1_manager_user_proto_rawDesc)))
	})
	return file_v1_manager_user_proto_rawDescData
}

var file_v1_manager_user_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_v1_manager_user_proto_goTypes = []any{
	(*User)(nil), // 0: v1.manager.User
}
var file_v1_manager_user_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_manager_user_proto_init() }
func file_v1_manager_user_proto_init() {
	if File_v1_manager_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_manager_user_proto_rawDesc), len(file_v1_manager_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_manager_user_proto_goTypes,
		DependencyIndexes: file_v1_manager_user_proto_depIdxs,
		MessageInfos:      file_v1_manager_user_proto_msgTypes,
	}.Build()
	File_v1_manager_user_proto = out.File
	file_v1_manager_user_proto_goTypes = nil
	file_v1_manager_user_proto_depIdxs = nil
}
