// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: v1/manager/verifier.proto

package manager

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VerifierStage int32

const (
	VerifierStage_VERIFIER_STAGE_EMAIL VerifierStage = 0
	VerifierStage_VERIFIER_STAGE_CODE  VerifierStage = 1
)

// Enum value maps for VerifierStage.
var (
	VerifierStage_name = map[int32]string{
		0: "VERIFIER_STAGE_EMAIL",
		1: "VERIFIER_STAGE_CODE",
	}
	VerifierStage_value = map[string]int32{
		"VERIFIER_STAGE_EMAIL": 0,
		"VERIFIER_STAGE_CODE":  1,
	}
)

func (x VerifierStage) Enum() *VerifierStage {
	p := new(VerifierStage)
	*p = x
	return p
}

func (x VerifierStage) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VerifierStage) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_manager_verifier_proto_enumTypes[0].Descriptor()
}

func (VerifierStage) Type() protoreflect.EnumType {
	return &file_v1_manager_verifier_proto_enumTypes[0]
}

func (x VerifierStage) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VerifierStage.Descriptor instead.
func (VerifierStage) EnumDescriptor() ([]byte, []int) {
	return file_v1_manager_verifier_proto_rawDescGZIP(), []int{0}
}

type Verifier struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stage         VerifierStage          `protobuf:"varint,1,opt,name=stage,proto3,enum=v1.manager.VerifierStage" json:"stage,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Verifier) Reset() {
	*x = Verifier{}
	mi := &file_v1_manager_verifier_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Verifier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Verifier) ProtoMessage() {}

func (x *Verifier) ProtoReflect() protoreflect.Message {
	mi := &file_v1_manager_verifier_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Verifier.ProtoReflect.Descriptor instead.
func (*Verifier) Descriptor() ([]byte, []int) {
	return file_v1_manager_verifier_proto_rawDescGZIP(), []int{0}
}

func (x *Verifier) GetStage() VerifierStage {
	if x != nil {
		return x.Stage
	}
	return VerifierStage_VERIFIER_STAGE_EMAIL
}

func (x *Verifier) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Verifier) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

var File_v1_manager_verifier_proto protoreflect.FileDescriptor

const file_v1_manager_verifier_proto_rawDesc = "" +
	"\n" +
	"\x19v1/manager/verifier.proto\x12\n" +
	"v1.manager\"e\n" +
	"\bVerifier\x12/\n" +
	"\x05stage\x18\x01 \x01(\x0e2\x19.v1.manager.VerifierStageR\x05stage\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code*B\n" +
	"\rVerifierStage\x12\x18\n" +
	"\x14VERIFIER_STAGE_EMAIL\x10\x00\x12\x17\n" +
	"\x13VERIFIER_STAGE_CODE\x10\x01B,Z*github.com/megakuul/zen/pkg/api/v1/managerb\x06proto3"

var (
	file_v1_manager_verifier_proto_rawDescOnce sync.Once
	file_v1_manager_verifier_proto_rawDescData []byte
)

func file_v1_manager_verifier_proto_rawDescGZIP() []byte {
	file_v1_manager_verifier_proto_rawDescOnce.Do(func() {
		file_v1_manager_verifier_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_manager_verifier_proto_rawDesc), len(file_v1_manager_verifier_proto_rawDesc)))
	})
	return file_v1_manager_verifier_proto_rawDescData
}

var file_v1_manager_verifier_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_manager_verifier_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_v1_manager_verifier_proto_goTypes = []any{
	(VerifierStage)(0), // 0: v1.manager.VerifierStage
	(*Verifier)(nil),   // 1: v1.manager.Verifier
}
var file_v1_manager_verifier_proto_depIdxs = []int32{
	0, // 0: v1.manager.Verifier.stage:type_name -> v1.manager.VerifierStage
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_v1_manager_verifier_proto_init() }
func file_v1_manager_verifier_proto_init() {
	if File_v1_manager_verifier_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_manager_verifier_proto_rawDesc), len(file_v1_manager_verifier_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_manager_verifier_proto_goTypes,
		DependencyIndexes: file_v1_manager_verifier_proto_depIdxs,
		EnumInfos:         file_v1_manager_verifier_proto_enumTypes,
		MessageInfos:      file_v1_manager_verifier_proto_msgTypes,
	}.Build()
	File_v1_manager_verifier_proto = out.File
	file_v1_manager_verifier_proto_goTypes = nil
	file_v1_manager_verifier_proto_depIdxs = nil
}
