// @generated by protoc-gen-es v2.7.0 with parameter "target=ts"
// @generated from file v1/scheduler/timing/timing.proto (package v1.scheduler.timing, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_v1_scheduler_event } from "../event_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file v1/scheduler/timing/timing.proto.
 */
export const file_v1_scheduler_timing_timing: GenFile = /*@__PURE__*/
  fileDesc("CiB2MS9zY2hlZHVsZXIvdGltaW5nL3RpbWluZy5wcm90bxITdjEuc2NoZWR1bGVyLnRpbWluZyIiCgxTdGFydFJlcXVlc3QSEgoKc3RhcnRfdGltZRgCIAEoAyIPCg1TdGFydFJlc3BvbnNlIiAKC1N0b3BSZXF1ZXN0EhEKCXN0b3BfdGltZRgCIAEoAyIOCgxTdG9wUmVzcG9uc2UysAEKDVRpbWluZ1NlcnZpY2USUAoFU3RhcnQSIS52MS5zY2hlZHVsZXIudGltaW5nLlN0YXJ0UmVxdWVzdBoiLnYxLnNjaGVkdWxlci50aW1pbmcuU3RhcnRSZXNwb25zZSIAEk0KBFN0b3ASIC52MS5zY2hlZHVsZXIudGltaW5nLlN0b3BSZXF1ZXN0GiEudjEuc2NoZWR1bGVyLnRpbWluZy5TdG9wUmVzcG9uc2UiAEI1WjNnaXRodWIuY29tL21lZ2FrdXVsL3plbi9wa2cvYXBpL3YxL3NjaGVkdWxlci90aW1pbmdiBnByb3RvMw", [file_v1_scheduler_event]);

/**
 * @generated from message v1.scheduler.timing.StartRequest
 */
export type StartRequest = Message<"v1.scheduler.timing.StartRequest"> & {
  /**
   * @generated from field: int64 start_time = 2;
   */
  startTime: bigint;
};

/**
 * Describes the message v1.scheduler.timing.StartRequest.
 * Use `create(StartRequestSchema)` to create a new message.
 */
export const StartRequestSchema: GenMessage<StartRequest> = /*@__PURE__*/
  messageDesc(file_v1_scheduler_timing_timing, 0);

/**
 * @generated from message v1.scheduler.timing.StartResponse
 */
export type StartResponse = Message<"v1.scheduler.timing.StartResponse"> & {
};

/**
 * Describes the message v1.scheduler.timing.StartResponse.
 * Use `create(StartResponseSchema)` to create a new message.
 */
export const StartResponseSchema: GenMessage<StartResponse> = /*@__PURE__*/
  messageDesc(file_v1_scheduler_timing_timing, 1);

/**
 * @generated from message v1.scheduler.timing.StopRequest
 */
export type StopRequest = Message<"v1.scheduler.timing.StopRequest"> & {
  /**
   * @generated from field: int64 stop_time = 2;
   */
  stopTime: bigint;
};

/**
 * Describes the message v1.scheduler.timing.StopRequest.
 * Use `create(StopRequestSchema)` to create a new message.
 */
export const StopRequestSchema: GenMessage<StopRequest> = /*@__PURE__*/
  messageDesc(file_v1_scheduler_timing_timing, 2);

/**
 * @generated from message v1.scheduler.timing.StopResponse
 */
export type StopResponse = Message<"v1.scheduler.timing.StopResponse"> & {
};

/**
 * Describes the message v1.scheduler.timing.StopResponse.
 * Use `create(StopResponseSchema)` to create a new message.
 */
export const StopResponseSchema: GenMessage<StopResponse> = /*@__PURE__*/
  messageDesc(file_v1_scheduler_timing_timing, 3);

/**
 * @generated from service v1.scheduler.timing.TimingService
 */
export const TimingService: GenService<{
  /**
   * @generated from rpc v1.scheduler.timing.TimingService.Start
   */
  start: {
    methodKind: "unary";
    input: typeof StartRequestSchema;
    output: typeof StartResponseSchema;
  },
  /**
   * @generated from rpc v1.scheduler.timing.TimingService.Stop
   */
  stop: {
    methodKind: "unary";
    input: typeof StopRequestSchema;
    output: typeof StopResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_v1_scheduler_timing_timing, 0);

